client_id = "b8dac1505617bff2043d38bcc7a6f6c2"
name = "Respondro"
application_url = "https://www.respondro.ai"
embedded = false

[access_scopes]
scopes = "read_orders,write_orders,read_customers,write_customers,read_fulfillments,read_products,read_inventory"

[auth]
redirect_urls = [
  "https://www.respondro.ai/api/shopify-callback"
]

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://www.respondro.ai/api/webhooks/gdpr/customers-redact"
  customer_data_request_url = "https://www.respondro.ai/api/webhooks/gdpr/customers-data-request"
  shop_deletion_url = "https://www.respondro.ai/api/webhooks/gdpr/shop-redact"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/api/webhooks/app-subscriptions-update"